# Generated by Django 5.0.1 on 2024-02-15 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brandmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('car_name', models.CharField(max_length=50)),
                ('car_price', models.IntegerField(null=True)),
                ('car_brand_name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brandmodel.barndmodel', verbose_name='Brand')),
            ],
        ),
    ]
