# Generated by Django 5.0.1 on 2024-02-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='car_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='carmodel.carmodel'),
            preserve_default=False,
        ),
    ]
