# Generated by Django 5.0.1 on 2024-02-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicians',
            new_name='Musician',
        ),
    ]
