# Generated by Django 5.0.1 on 2024-01-31 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_release_date', models.DateField(auto_now_add=True)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician_model')),
            ],
        ),
    ]
