# Generated by Django 5.0.1 on 2024-01-31 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_model_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_model',
            name='album_release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
