# Generated by Django 5.0.1 on 2024-01-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emal', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('instrument_type', models.CharField(max_length=50)),
            ],
        ),
    ]
