# Generated by Django 5.0.1 on 2024-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_discription', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('task_asgin_date', models.DateField()),
                ('category', models.ManyToManyField(to='taskCategory.category_model')),
            ],
        ),
    ]
